import { WeatherCodes } from '.';

// icons from http://erikflowers.github.io/weather-icons/
export let WeatherIcons = {
    [WeatherCodes.Tornado]: 'wi-tornado',
    [WeatherCodes.TropicalStorm]: '',
    [WeatherCodes.Hurricane]: '',
    [WeatherCodes.SevereThunderstorms]: '',
    [WeatherCodes.Thunderstorms]: '',
    [WeatherCodes.MixedRainSnow]: '',
    [WeatherCodes.MixedRainSleet]: '',
    [WeatherCodes.MixedSnowSleet]: '',
    [WeatherCodes.FreezingDrizzle]: '',
    [WeatherCodes.Drizzle]: '',
    [WeatherCodes.FreezingRain]: '',
    [WeatherCodes.ShowersNight]: '',
    [WeatherCodes.ShowersDay]: '',
    [WeatherCodes.SnowFlurries]: '',
    [WeatherCodes.LightSnowShowers]: '',
    [WeatherCodes.BlowingSnow]: '',
    [WeatherCodes.Snow]: '',
    [WeatherCodes.Hail]: '',
    [WeatherCodes.Sleet]: '',
    [WeatherCodes.Dust]: '',
    [WeatherCodes.Foggy]: '',
    [WeatherCodes.Haze]: '',
    [WeatherCodes.Smoky]: '',
    [WeatherCodes.Blustery]: '',
    [WeatherCodes.Windy]: '',
    [WeatherCodes.Cold]: '',
    [WeatherCodes.Cloudy]: '',
    [WeatherCodes.MostlyCloudyNight]: '',
    [WeatherCodes.MostlyCloudyDay]: '',
    [WeatherCodes.PartlyCloudyNight]: '',
    [WeatherCodes.PartlyCloudyDay]: '',
    [WeatherCodes.ClearNight]: '',
    [WeatherCodes.Sunny]: '',
    [WeatherCodes.FairNight]: '',
    [WeatherCodes.FairDay]: '',
    [WeatherCodes.MixedRainAndHail]: '',
    [WeatherCodes.Hot]: '',
    [WeatherCodes.IsolatedThunderstorms]: '',
    [WeatherCodes.ScatteredThunderstormsNight]: '',
    [WeatherCodes.ScatteredThunderstormsDay]: '',
    [WeatherCodes.ScatteredShowers]: '',
    [WeatherCodes.HeavySnowNight]: '',
    [WeatherCodes.ScatteredSnowShowers]: '',
    [WeatherCodes.HeavySnowDay]: '',
    [WeatherCodes.PartlyCloudy]: '',
    [WeatherCodes.Thundershowers]: '',
    [WeatherCodes.SnowShowers]: '',
    [WeatherCodes.IsolatedThundershowers]: '',
    [WeatherCodes.NotAvailable]: '',
};